-- GERADO por scripts/generate-seed-sql.ts a partir de src/data/seed/menu.ts. Não edite à mão.
-- ⚠️ Não aplicar em nenhum projeto remoto sem autorização explícita do dono do projeto.
begin;
truncate table public.promotions, public.dish_addons, public.dish_variants, public.dishes, public.categories, public.opening_hours, public.restaurant restart identity cascade;

insert into public.restaurant (name, tagline, address, maps_url, timezone, prep_time_minutes, payment_methods, payment_notes, notes) values ('Divino Fogão', 'Comida da Fazenda · São Leopoldo', 'Bourbon Shopping São Leopoldo · R. Primeiro de Março, 821 · Centro, São Leopoldo/RS', 'https://www.google.com/maps/search/?api=1&query=Divino+Fog%C3%A3o+Bourbon+Shopping+S%C3%A3o+Leopoldo', 'America/Sao_Paulo', 20, array['Pix', 'Visa', 'Mastercard', 'Elo', 'Hipercard', 'American Express', 'VR', 'Alelo', 'Sodexo', 'Pluxee', 'Ticket', 'GreenCard', 'Aproximação']::text[], array['Não aceitamos Banrisul.']::text[], array['Todos os pratos acompanham salada de tomate, alface e cenoura.']::text[]);

insert into public.opening_hours (weekday, opens_at, closes_at) values (1, '11:00', '22:00');
insert into public.opening_hours (weekday, opens_at, closes_at) values (2, '11:00', '22:00');
insert into public.opening_hours (weekday, opens_at, closes_at) values (3, '11:00', '22:00');
insert into public.opening_hours (weekday, opens_at, closes_at) values (4, '11:00', '22:00');
insert into public.opening_hours (weekday, opens_at, closes_at) values (5, '11:00', '22:00');
insert into public.opening_hours (weekday, opens_at, closes_at) values (6, '11:00', '22:00');
insert into public.opening_hours (weekday, opens_at, closes_at) values (0, '11:00', '21:00');

insert into public.categories (slug, name, display_style, position) values ('porcoes-divinas', 'Porções Divinas', 'rows', 0);
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'pao-de-alho', 'Pão de alho', null, null, null, null, '{}'::text[], true, false, 0 from public.categories where slug = 'porcoes-divinas';
insert into public.dish_variants (dish_id, label, price, position) select id, '3 unidades', 18.90, 0 from public.dishes where slug = 'pao-de-alho';
insert into public.dish_variants (dish_id, label, price, position) select id, '1 unidade', 6.90, 1 from public.dishes where slug = 'pao-de-alho';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'batata-frita', 'Batata frita', null, null, null, null, '{}'::text[], true, false, 1 from public.categories where slug = 'porcoes-divinas';
insert into public.dish_variants (dish_id, label, price, position) select id, 'Pequena', 29.90, 0 from public.dishes where slug = 'batata-frita';
insert into public.dish_variants (dish_id, label, price, position) select id, 'Grande', 42.90, 1 from public.dishes where slug = 'batata-frita';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'polenta-frita', 'Polenta frita', null, 27.90, null, null, '{}'::text[], true, false, 2 from public.categories where slug = 'porcoes-divinas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'ovo-de-codorna-com-oregano', 'Ovo de codorna com orégano', null, 35.90, null, null, '{}'::text[], true, false, 3 from public.categories where slug = 'porcoes-divinas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'tomatinho-cereja', 'Tomatinho cereja', 'Temperado com sal, azeite de oliva e orégano.', 35.90, null, null, '{}'::text[], true, false, 4 from public.categories where slug = 'porcoes-divinas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'pepino-em-conserva', 'Pepino em conserva', null, 35.90, null, null, '{}'::text[], true, false, 5 from public.categories where slug = 'porcoes-divinas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'aneis-de-cebola', 'Anéis de cebola', null, 35.90, null, null, '{}'::text[], true, false, 6 from public.categories where slug = 'porcoes-divinas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'calabresa-grelhada', 'Calabresa grelhada', 'Acebolada.', 35.90, null, null, '{}'::text[], true, false, 7 from public.categories where slug = 'porcoes-divinas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'tiras-de-file-de-frango', 'Tiras de filé de frango grelhado', 'Aceboladas.', 35.90, null, null, '{}'::text[], true, false, 8 from public.categories where slug = 'porcoes-divinas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'tiras-de-alcatra', 'Tiras de alcatra grelhada', 'Aceboladas.', 51.90, null, null, '{}'::text[], true, false, 9 from public.categories where slug = 'porcoes-divinas';

insert into public.categories (slug, name, display_style, position) values ('para-compartilhar', 'Para Compartilhar', 'rows', 1);
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'porcao-dupla', 'Porção dupla', 'Escolha 2 opções diferentes: batata frita, polenta frita, pão de alho, ovo de codorna, pepino em conserva, calabresa acebolada, iscas de frango aceboladas, iscas de alcatra aceboladas, tomatinho cereja ou anéis de cebola.', 39.90, null, null, '{}'::text[], true, false, 0 from public.categories where slug = 'para-compartilhar';
insert into public.dish_addons (dish_id, label, price, position) select id, 'Opção com alcatra', 5.00, 0 from public.dishes where slug = 'porcao-dupla';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'batata-frita-com-calabresa', 'Batata frita com calabresa', null, 39.00, 'batata-com-calabresa.jpg', null, '{}'::text[], true, true, 1 from public.categories where slug = 'para-compartilhar';
insert into public.dish_addons (dish_id, label, price, position) select id, 'Opção com alcatra', 5.00, 0 from public.dishes where slug = 'batata-frita-com-calabresa';
insert into public.dish_addons (dish_id, label, price, position) select id, 'Farofinha', 5.00, 1 from public.dishes where slug = 'batata-frita-com-calabresa';
insert into public.dish_addons (dish_id, label, price, position) select id, 'Cebolado extra', 5.00, 2 from public.dishes where slug = 'batata-frita-com-calabresa';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'divina-porcao', 'Divina Porção', 'Batata frita, pão de alho, iscas de alcatra, iscas de frango, calabresa acebolada, tomatinho cereja, ovinho de codorna com orégano, pepino e queijo coalho.', 89.90, null, 3, '{}'::text[], true, true, 2 from public.categories where slug = 'para-compartilhar';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'batatao-divino', 'Batatão Divino', 'Escolha os recheios: cheddar, barbecue, calabresa ou muçarela; estrogonofe de frango com batata palha; ou estrogonofe de carne com batata palha. Ganhe 1 chopp 400 ml.', 89.90, 'batatao.jpg', 3, '{}'::text[], true, true, 3 from public.categories where slug = 'para-compartilhar';

insert into public.categories (slug, name, display_style, position) values ('parmegianas', 'Parmegianas', 'rows', 2);
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'parmegiana-de-frango', 'Parmegiana de frango', 'Molho artesanal. Acompanha arroz branco ou integral e batata frita, batata palha ou legumes.', 45.90, null, null, '{}'::text[], true, true, 0 from public.categories where slug = 'parmegianas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'parmegiana-de-tilapia', 'Parmegiana de tilápia', 'Molho artesanal. Acompanha arroz branco ou integral e batata frita, batata palha ou legumes.', null, null, null, '{}'::text[], true, false, 1 from public.categories where slug = 'parmegianas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'parmegiana-de-alcatra', 'Parmegiana de alcatra', 'Molho artesanal. Acompanha arroz branco ou integral e batata frita, batata palha ou legumes.', 47.90, null, null, '{}'::text[], true, false, 2 from public.categories where slug = 'parmegianas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'parmegiana-de-berinjela', 'Parmegiana de berinjela', 'Molho artesanal. Acompanha arroz branco ou integral e batata frita, batata palha ou legumes.', null, null, null, array['vegetariano']::text[], true, false, 3 from public.categories where slug = 'parmegianas';

insert into public.categories (slug, name, display_style, position) values ('pratos-com-frango', 'Frango', 'rows', 3);
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'file-de-frango-grelhado', 'Filé de frango grelhado', 'Acompanha feijão carioca, preto ou lentilha; arroz branco ou integral; e batata frita ou palha.', 39.90, null, null, '{}'::text[], true, false, 0 from public.categories where slug = 'pratos-com-frango';
insert into public.dish_addons (dish_id, label, price, position) select id, 'À milanesa', 3.00, 0 from public.dishes where slug = 'file-de-frango-grelhado';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'estrogonofe-de-frango', 'Estrogonofe de frango', 'Acompanha arroz branco ou integral e batata frita, batata palha ou legumes.', 41.90, null, null, '{}'::text[], true, false, 1 from public.categories where slug = 'pratos-com-frango';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'file-de-frango-com-legumes', 'Filé de frango com legumes', 'Acompanha feijão carioca, preto ou lentilha e arroz branco ou integral.', 39.90, null, null, '{}'::text[], true, false, 2 from public.categories where slug = 'pratos-com-frango';

insert into public.categories (slug, name, display_style, position) values ('carnes-e-peixe', 'Carnes e Peixe', 'rows', 4);
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'alcatra-a-cavalo', 'Alcatra à cavalo à la minuta', 'Com ovo frito. Acompanha feijão carioca, preto ou lentilha; arroz branco ou integral; e batata frita ou palha.', 45.90, null, null, '{}'::text[], true, false, 0 from public.categories where slug = 'carnes-e-peixe';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'alcatra-grelhada', 'Alcatra grelhada', 'Acompanha feijão carioca, preto ou lentilha; arroz branco ou integral; e batata frita ou palha.', 43.90, null, null, '{}'::text[], true, false, 1 from public.categories where slug = 'carnes-e-peixe';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'tilapia-grelhada', 'Tilápia grelhada', 'Acompanha arroz branco ou integral e batata frita, batata palha ou legumes.', 47.90, null, null, '{}'::text[], true, false, 2 from public.categories where slug = 'carnes-e-peixe';
insert into public.dish_addons (dish_id, label, price, position) select id, 'À milanesa', 3.00, 0 from public.dishes where slug = 'tilapia-grelhada';

insert into public.categories (slug, name, display_style, position) values ('extras', 'Extras', 'compact', 5);
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'arroz-branco', 'Arroz branco', null, 9.90, null, null, '{}'::text[], true, false, 0 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'arroz-integral', 'Arroz integral', null, 11.90, null, null, '{}'::text[], true, false, 1 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'batata-frita-na-caixinha', 'Batata frita na caixinha', null, 11.90, null, null, '{}'::text[], true, false, 2 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'alcatra-extra', 'Alcatra (100–120 g)', null, 15.90, null, null, '{}'::text[], true, false, 3 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'ovo-frito', 'Ovo frito (1 unidade)', null, 3.90, null, null, '{}'::text[], true, false, 4 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'polenta-frita-pequena', 'Polenta frita (pequena)', null, 11.90, null, null, '{}'::text[], true, false, 5 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'legumes', 'Legumes', null, 11.90, null, null, '{}'::text[], true, false, 6 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'feijao-carioca', 'Feijão carioca', null, 11.90, null, null, '{}'::text[], true, false, 7 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'feijao-preto', 'Feijão preto', null, 11.90, null, null, '{}'::text[], true, false, 8 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'lentilha', 'Lentilha', null, 13.90, null, null, '{}'::text[], true, false, 9 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'file-de-frango-extra', 'Filé de frango (100–120 g)', null, 13.90, null, null, '{}'::text[], true, false, 10 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'pure-de-batata', 'Purê de batata', null, 11.90, null, null, '{}'::text[], true, false, 11 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'tilapia-extra', 'Tilápia grelhada (100–120 g)', null, 17.90, null, null, '{}'::text[], true, false, 12 from public.categories where slug = 'extras';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'maionese', 'Maionese (300 g)', null, 13.90, null, null, '{}'::text[], true, false, 13 from public.categories where slug = 'extras';

insert into public.categories (slug, name, display_style, position) values ('sobremesas', 'Sobremesas', 'compact', 6);
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'mousse-de-maracuja', 'Mousse de maracujá', null, 9.90, null, null, '{}'::text[], true, false, 0 from public.categories where slug = 'sobremesas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'mousse-de-limao', 'Mousse de limão', null, 9.90, null, null, '{}'::text[], true, false, 1 from public.categories where slug = 'sobremesas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'fatia-de-pudim', 'Fatia de pudim', null, 9.90, null, null, '{}'::text[], true, false, 2 from public.categories where slug = 'sobremesas';

insert into public.categories (slug, name, display_style, position) values ('bebidas', 'Bebidas', 'compact', 7);
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'refrigerante', 'Refrigerante', null, null, null, null, '{}'::text[], true, false, 0 from public.categories where slug = 'bebidas';
insert into public.dish_variants (dish_id, label, price, position) select id, 'Lata', 9.50, 0 from public.dishes where slug = 'refrigerante';
insert into public.dish_variants (dish_id, label, price, position) select id, '600 ml', 13.50, 1 from public.dishes where slug = 'refrigerante';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'suco-del-valle', 'Suco Del Valle (lata)', null, 9.50, null, null, '{}'::text[], true, false, 1 from public.categories where slug = 'bebidas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'agua-tonica', 'Água tônica', null, 9.50, null, null, '{}'::text[], true, false, 2 from public.categories where slug = 'bebidas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'schweppes-citrus', 'Schweppes Citrus', null, 9.50, null, null, '{}'::text[], true, false, 3 from public.categories where slug = 'bebidas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'cha-gelado', 'Chá gelado (copo)', null, 9.90, null, null, '{}'::text[], true, false, 4 from public.categories where slug = 'bebidas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'agua-mineral', 'Água mineral 500 ml', null, 7.50, null, null, '{}'::text[], true, false, 5 from public.categories where slug = 'bebidas';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'suco-de-laranja', 'Suco de laranja natural', null, null, null, null, '{}'::text[], true, false, 6 from public.categories where slug = 'bebidas';
insert into public.dish_variants (dish_id, label, price, position) select id, '200 ml', 9.00, 0 from public.dishes where slug = 'suco-de-laranja';
insert into public.dish_variants (dish_id, label, price, position) select id, '300 ml', 11.00, 1 from public.dishes where slug = 'suco-de-laranja';
insert into public.dish_variants (dish_id, label, price, position) select id, '500 ml', 13.00, 2 from public.dishes where slug = 'suco-de-laranja';

insert into public.categories (slug, name, display_style, position) values ('cervejas-e-drinks', 'Cervejas e Drinks', 'compact', 8);
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'chopp', 'Chopp', null, null, null, null, '{}'::text[], true, false, 0 from public.categories where slug = 'cervejas-e-drinks';
insert into public.dish_variants (dish_id, label, price, position) select id, '400 ml', 19.00, 0 from public.dishes where slug = 'chopp';
insert into public.dish_variants (dish_id, label, price, position) select id, '770 ml', 29.00, 1 from public.dishes where slug = 'chopp';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'cerveja-long-neck', 'Cerveja long neck', null, 15.00, null, null, '{}'::text[], true, false, 1 from public.categories where slug = 'cervejas-e-drinks';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'cerveja-lata', 'Cerveja lata', null, 11.00, null, null, '{}'::text[], true, false, 2 from public.categories where slug = 'cervejas-e-drinks';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'cerveja-latao', 'Cerveja latão 473 ml', null, 16.00, null, null, '{}'::text[], true, false, 3 from public.categories where slug = 'cervejas-e-drinks';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'caipirinha-de-cachaca', 'Caipirinha de cachaça', null, 25.00, null, null, '{}'::text[], true, false, 4 from public.categories where slug = 'cervejas-e-drinks';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'caipirinha-de-vodka', 'Caipirinha de vodka', null, 29.00, null, null, '{}'::text[], true, false, 5 from public.categories where slug = 'cervejas-e-drinks';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'cachaca-mineira', 'Cachaça mineira (dose)', null, 11.00, null, null, '{}'::text[], true, false, 6 from public.categories where slug = 'cervejas-e-drinks';
insert into public.dishes (category_id, slug, name, description, base_price, photo_path, serves, tags, is_available, is_featured, position) select id, 'whisky-importado', 'Whisky importado (dose)', null, 19.00, null, null, '{}'::text[], true, false, 7 from public.categories where slug = 'cervejas-e-drinks';

insert into public.promotions (slug, title, description, highlight, photo_path, dish_id, position) values ('prato-mais-bebida', 'Prato + bebida', 'Na compra de qualquer prato, leve um refrigerante lata ou uma água mineral 500 ml.', '+ R$ 5,90', null, null, 0);
insert into public.promotions (slug, title, description, highlight, photo_path, dish_id, position) values ('tres-chopps-com-fritas', '3 chopps + fritas', 'Na compra de 3 chopps 400 ml, acrescente R$ 2,00 e ganhe uma mini porção de batata frita.', '+ R$ 2,00', null, null, 1);
insert into public.promotions (slug, title, description, highlight, photo_path, dish_id, position) values ('caipirinha-com-long-neck', 'Caipirinha + long neck', 'Na compra de uma caipirinha, ganhe 1 cerveja long neck (Stella Artois ou Budweiser).', 'Long neck grátis', null, null, 2);
insert into public.promotions (slug, title, description, highlight, photo_path, dish_id, position) values ('sobremesa-terceira-gratis', 'Sobremesas', 'Na compra de duas sobremesas, a terceira é grátis.', '3ª grátis', null, null, 3);
commit;
